site_name: Skoving
site_url: https://skoveit.github.io/skoving/

repo_url: https://github.com/skoveit/skoving
repo_name: skoveit/skoving

copyright: ""

extra:
  generator: false
  analytics:
    provider: google
    property: G-QTX3WF018B

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.tabs              # القائمة العلوية
    - navigation.sections          # تقسيم المحتوى لسكاشن
    - navigation.expand            # <--- امسح السطر ده أو عطلّه
    - navigation.path              # بيخلي المسار الحالي واضح
    - navigation.indexes           # بيخلي العناوين الرئيسية قابلة للضغط
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
  palette:
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Dark mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


nav:
  - Home: index.md

  - SkoveNet:
      - Overview: projects/skovenet/index.md

      - Getting Started:
          - Installation: projects/skovenet/getting-started/installation.md
          - Quickstart: projects/skovenet/getting-started/quickstart.md

      - Architecture:
          - Overview: projects/skovenet/architecture/overview.md
          - Networking: projects/skovenet/architecture/networking.md
          - Security: projects/skovenet/architecture/security.md

      - Features:
          - Discovery: projects/skovenet/features/discovery.md
          - Commands: projects/skovenet/features/commands.md

      - Development:
          - Roadmap: projects/skovenet/development/roadmap.md
          - Contributing: projects/skovenet/development/contributing.md

      - Troubleshooting: projects/skovenet/troubleshooting.md

  - Writeups:
      - Overview: writeups/index.md
      - Web:
          - FTPbox Hardcoded Credentials: writeups/web/FTPbox.md
          - JavaScript Recon to PII Exposure: writeups/web/PII-discl.md
      - Maldev:
          - Payload Hiding: writeups/maldev/payload-Hiding.md


  - Notes:
      - Overview: notes/index.md

      - Windows Internals:
          - DLL: notes/windows internals/DLL.md
          - PE Structure: notes/windows internals/PE structure.md
          - Processes: notes/windows internals/process.md
          - Security: notes/windows internals/security.md
          - Memory:
              - Memory Mapping: notes/windows internals/memory/memory mapping.md

      - Active Directory:
          - Certificate Services: notes/active directory/Certificate Services.md
          - Kerberos: notes/active directory/Kerbros.md
          - LAPS: notes/active directory/LAPS.md
      - Red Team:
          - Proxying: notes/red/proxying.md
          - Windows:
              - Active Directory Techniques: notes/red/windows/Active directory techniques.md
              - Initial Access (0%):
                  - AD Enumeration: notes/red/windows/0%/AD-enum.md
                  - Zero: notes/red/windows/0%/Zero.md
                  - Send Payload: notes/red/windows/0%/send payload.md
              - Foothold (10%): 
                  - Foothold: notes/red/windows/10%/foothold.md
              - Post Exploitation (70%):
                  - Enumeration: notes/red/windows/70%/Enum.md
                  - Exfiltration: notes/red/windows/70%/ExFil.md
                  - Privilege Escalation: notes/red/windows/70%/PrivEsc.md
                  - Lateral Movement: notes/red/windows/70%/Leteral Movement/Leteral Movement.md
                  - OPSEC: notes/red/windows/70%/OPSEC/OPSEC.md
                  - Persistence:
                      - AD Persistence: notes/red/windows/70%/persistence/AD persistance.md
                      - General Persistence: notes/red/windows/70%/persistence/persistence.md
      - Web Security:
          - CSRF: notes/web/CSRF.md
          - GraphQL: notes/web/GraphQL.md
          - HTTP Request Smuggling: notes/web/HTTP request smuggling.md
          - JWT: notes/web/JWT.md
          - Logic Flaws: notes/web/Logic-flaws.md
          - Race Condition: notes/web/Race Condition.md
          - WebSocket: notes/web/WebSocket.md

          
  - Research: research/index.md
